app/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from sqlalchemy.ext.declarative import declared_attr
import sqlalchemy as sa

migrate = Migrate()


class IdModel(object):
    @declared_attr
    def id(cls):
        for base in cls.__mro__[1:-1]:
            if getattr(base, "__table__", None) is not None:
                type = sa.ForeignKey(base.id)
                break
        else:
            type = sa.Integer

        return sa.Column(type, primary_key=True)


db = SQLAlchemy(model_class=IdModel)


class NameDescriptionMixin(object):
    name = db.Column(db.String(128))
    description = db.Column(db.Text())


class Skill(db.Model, NameDescriptionMixin):
    core = db.Column(db.Boolean())
    profession_id = db.Column(db.ForeignKey("profession.id"))


class SkillLevel(db.Model):
    skill_id = db.Column(db.ForeignKey("skill.id"))
    assessment_id = db.Column(db.ForeignKey("assessment.id"))
    value = db.Column(db.Integer())


class Profession(db.Model, NameDescriptionMixin):
    pass


class Role(db.Model):
    title = db.Column(db.String(128))

    profession_id = db.Column(db.ForeignKey("profession.id"))


class Posting(db.Model):
    candidate_id = db.Column(db.ForeignKey("candidate.id"))
    role_id = db.Column(db.ForeignKey("role.id"))

    date_started = db.Column(db.Date())
    date_ended = db.Column(db.Date())
    rotation_number = db.Column(db.Integer())


class Assessment(db.Model):
    posting_id = db.Column(db.ForeignKey("posting.id"))

    date = db.Column(db.Date())
    overall_mark = db.Column(db.String(56))

    posting = db.relationship("Posting")

    def candidate(self):
        return Candidate.query.get(self.posting.candidate_id)


class Candidate(db.Model):
    name = db.Column(db.String(128), nullable=False)
    email_address = db.Column(db.String(120), unique=True, nullable=False)
    secondary_email_address = db.Column(db.String(120), unique=True)
    joining_date = db.Column(db.Date(), nullable=False)
    location_restriction = db.Column(
        db.Boolean(), default=False, nullable=False
    )  # TRUE: yes, FALSE: no, NULL: Prefer not to say

    def __repr__(self):
        return f"<Candidate email {self.email_address}>"

    def update_email(self, new_address: str, primary: bool):
        if primary:
            self.email_address = new_address
        elif not primary:
            self.secondary_email_address = new_address

    def current_skill_level(self):
        pass

    def latest_assessment(self):
        pass

app/__init__.py
from flask import Flask
from config import Config


def create_app(configuration=Config):
    app = Flask(__name__, static_folder="static")

    from app.models import db, migrate

    app.config.from_object(configuration)
    db.init_app(app)
    migrate.init_app(app, db)

    from app.munkres_api import munkres_bp

    app.register_blueprint(munkres_bp, url_prefix="/munkres-api/v1/")

    from app.pitch import pitch_bp

    app.register_blueprint(pitch_bp, url_prefix="/pitch/")

    from app.main import main_bp

    app.register_blueprint(main_bp)

    from app.profile import profile_bp

    app.register_blueprint(profile_bp, url_prefix="/profile/")

    return app

app/main/__init__.py
from flask import Blueprint

main_bp = Blueprint("main", __name__)

from app.main import routes  # noqa: E402,F401

app/main/routes.py
from flask import render_template
from app.main import main_bp


@main_bp.route("/weighting", methods=["GET"])
def weighting():
    return render_template("weighting.html")

app/munkres_api/__init__.py
from flask import Blueprint

munkres_bp = Blueprint("munkres_api", __name__)

from app.munkres_api import routes  # noqa: E402,F401

app/munkres_api/routes.py
from app.munkres_api import munkres_bp
from munkres import Munkres
import json
from flask import request, jsonify
import sys


@munkres_bp.route("/process-matrix", methods=["POST"])
def process_matrix():
    """
    This api takes a list of lists and returns a list of coordinates. The list of list represents an n x m matrix of numbers. This function finds the path
    through the matrix that returns the highest value
    :return:
    """
    matrix = json.loads(request.data).get("matrix")
    cost_matrix = [[sys.maxsize - col for col in row] for row in matrix]
    m = Munkres()
    indexes = m.compute(cost_matrix)
    return jsonify(indexes)

app/pitch/__init__.py
from flask import Blueprint

pitch_bp = Blueprint("pitch", __name__)

from app.pitch import routes  # noqa: E402,F401

app/pitch/routes.py
import json
from flask import render_template, session, request, url_for
from app.pitch import pitch_bp
import requests
from random import randrange


@pitch_bp.route("/start", methods=["GET"])
def start():
    return render_template("pitch/start.html")


@pitch_bp.route("/situation", methods=["GET"])
def situation():
    return render_template("pitch/current-situation.html")


@pitch_bp.route("/the-problem", methods=["GET"])
def problem():
    return render_template("pitch/the-problem.html")


@pitch_bp.route("/the-approach", methods=["GET"])
def approach():
    semi_random_data = [[randrange(0, 25) for i in range(10)] for j in range(10)]
    session["matrix"] = semi_random_data
    return render_template("pitch/the-approach.html", data=semi_random_data)


@pitch_bp.route("/the-solution", methods=["POST"])
def solution():
    if request.method == "POST":
        result = requests.post(
            url_for("munkres_api.process_matrix", _external=True),
            data=json.dumps({"matrix": session["matrix"]}),
        )
        return render_template(
            "pitch/the-solution.html",
            indexes=json.loads(result.content),
            data=session["matrix"],
            lookup={i: chr(i + 65) for i in range(10)},
        )
    else:
        pass

app/profile/__init__.py
from flask import Blueprint

profile_bp = Blueprint("profile", __name__)

from app.profile import routes  # noqa: E402,F401

app/profile/routes.py
from flask import render_template
from app.profile import profile_bp


@profile_bp.route("/index", methods=["GET"])
def index():
    content = {
        "history": [
            {
                "id": 1,
                "title": "Finance manager",
                "anchor": "Finance",
                "evaluation": "Met",
            },
            {
                "id": 2,
                "title": "Assistant Product Manager",
                "anchor": "Digital",
                "evaluation": "Exceeded",
            },
        ],
        "candidate": {
            "first_name": "Antonia",
            "last_name": "Ivanovna",
            "specialism": "Property",
        },
    }

    return render_template("profile/profile.html", **content)

app/templates/base.html
<!DOCTYPE html>
<html lang="en" class="govuk-template ">

<head>
  <meta charset="utf-8" />
  <title>Talent Rotator</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <meta name="theme-color" content="#0b0c0c" />

  <meta http-equiv="X-UA-Compatible" content="IE=edge" />

{#  <link rel="shortcut icon" sizes="16x16 32x32 48x48" href="{{ url_for('static', filename='assets/images/favicon.ico') }}" type="image/x-icon" />#}
  <link rel="mask-icon" href="/assets/images/govuk-mask-icon.svg" color="#0b0c0c">
  <link rel="apple-touch-icon" sizes="180x180" href="/assets/images/govuk-apple-touch-icon-180x180.png">
  <link rel="apple-touch-icon" sizes="167x167" href="/assets/images/govuk-apple-touch-icon-167x167.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/assets/images/govuk-apple-touch-icon-152x152.png">
  <link rel="apple-touch-icon" href="/assets/images/govuk-apple-touch-icon.png">

  <!--[if !IE 8]><!-->
  <link href="{{ url_for('static', filename='css/main.css') }}"
      rel="stylesheet" type="text/css">
  <!--<![endif]-->

  <!--[if IE 8]>
    <link href="/govuk-frontend/all-ie8.css" rel="stylesheet" />
  <![endif]-->

  <!--[if lt IE 9]>
    <script src="/html5-shiv/html5shiv.js"></script>
  <![endif]-->

  <meta property="og:image" content="/assets/images/govuk-opengraph-image.png">
</head>

<body class="govuk-template__body ">
  <script>
    document.body.className = ((document.body.className) ? document.body.className + ' js-enabled' : 'js-enabled');

  </script>

  <a href="#main-content" class="govuk-skip-link">Skip to main content</a>

  <header class="govuk-header " role="banner" data-module="header">
    <div class="govuk-header__container govuk-width-container">
        <div class="govuk-header__content">

        <a href="{{ url_for('pitch.start') }}" class="govuk-header__link govuk-header__link--service-name">
          Talent rotator
        </a>

        <button type="button" role="button" class="govuk-header__menu-button js-header-toggle" aria-controls="navigation" aria-label="Show or hide Top Level Navigation">Menu</button>
            <nav>
          <ul id="navigation" class="govuk-header__navigation " aria-label="Top Level Navigation">
            <li class="govuk-header__navigation-item">
              <a class="govuk-header__link" href="{{ url_for("pitch.problem") }}">
                The problem
              </a>
            </li>
              <li class="govuk-header__navigation-item">
                  <a class="govuk-header__link" href="{{ url_for("main.weighting") }}">
                      Weighting
                  </a>
              </li>
          </ul>
        </nav>

        </div>
    </div>

  </header>

  <div class="govuk-width-container">
    <div class="govuk-phase-banner">
      <p class="govuk-phase-banner__content">
          <strong class="govuk-tag govuk-phase-banner__content__tag ">alpha</strong>
        <span class="govuk-phase-banner__text">
          This is an alpha. <a href="mailto:jonathan.drew.kerr+grad@gmail.com">Your feedback will help to improve it</a>
        </span>
      </p>
    </div>
    <main class="govuk-main-wrapper " id="main-content" role="main">
    {% if page_header %}
      <h1 class="govuk-heading-xl">{{ page_header }}</h1>
    {% endif %}
        {% block content %}
        {% endblock %}
    </main>
  </div>

  <footer class="govuk-footer " role="contentinfo">
    <div class="govuk-width-container ">
{#      <div class="govuk-footer__meta">#}
{#        <div class="govuk-footer__meta-item govuk-footer__meta-item--grow">#}
{##}
{#          <svg role="presentation" focusable="false" class="govuk-footer__licence-logo" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 483.2 195.7" height="17" width="41">#}
{#            <path fill="currentColor" d="M421.5 142.8V.1l-50.7 32.3v161.1h112.4v-50.7zm-122.3-9.6A47.12 47.12 0 0 1 221 97.8c0-26 21.1-47.1 47.1-47.1 16.7 0 31.4 8.7 39.7 21.8l42.7-27.2A97.63 97.63 0 0 0 268.1 0c-36.5 0-68.3 20.1-85.1 49.7A98 98 0 0 0 97.8 0C43.9 0 0 43.9 0 97.8s43.9 97.8 97.8 97.8c36.5 0 68.3-20.1 85.1-49.7a97.76 97.76 0 0 0 149.6 25.4l19.4 22.2h3v-87.8h-80l24.3 27.5zM97.8 145c-26 0-47.1-21.1-47.1-47.1s21.1-47.1 47.1-47.1 47.2 21 47.2 47S123.8 145 97.8 145" />#}
{#          </svg>#}
{#          <span class="govuk-footer__licence-description">#}
{#            All content is available under the#}
{#            <a class="govuk-footer__link" href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" rel="license">Open Government Licence v3.0</a>, except where otherwise stated#}
{#          </span>#}
{#        </div>#}
{#        <div class="govuk-footer__meta-item">#}
{#          <a class="govuk-footer__link govuk-footer__copyright-logo" href="https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/uk-government-licensing-framework/crown-copyright/">© Crown copyright</a>#}
{#        </div>#}
{#      </div>#}
    </div>
  </footer>

  <script src="/static/all.js"></script>
  <script>
    window.GOVUKFrontend.initAll()

  </script>
</body>

</html>

app/templates/partials/accordion-section-role.html
<div class="govuk-accordion__section ">
    <div class="govuk-accordion__section-header">
        <h2 class="govuk-accordion__section-heading">
        <span class="govuk-accordion__section-button" id="accordion-default-heading-{{ loop.index + 1 }}">
          {{ role.title }} ({{ role.anchor }})
        </span>
        </h2>
    </div>
    <div id="accordion-default-content-{{ loop.index + 1 }}" class="govuk-accordion__section-content" aria-labelledby="accordion-default-heading-{{ loop.index + 1 }}">
        <ul class="govuk-list govuk-list--bullet">
            <li>{{ candidate.first_name }} was given a marking of "{{ role.evaluation }}"</li>
        </ul>
    </div>
</div>

app/templates/partials/table-cell.html
<td class="govuk-table__cell">{{ value }}</td>

app/templates/partials/table-row.html
<tr class="govuk-table__row">
    <th scope="row" class="govuk-table__header">Role {{ j }}</th>
    {% for value in row %}
        {% include "partials/table-cell.html" %}
    {% endfor %}
</tr>

app/templates/pitch/current-situation.html
{% extends "base.html" %}

{% block content %}
    <h1 class="govuk-heading-l">How does this work at the moment?</h1>
    <p class="govuk-body-lead">
        In most large organisations, this process is carried out manually. Staff shuffle big
        piles of paper and try to remember what they've seen and if it would be suitable. It's
        a lot of effort, and never - despite best efforts - seems to work out particularly well.
        There's a really good reason for this: it's almost impossible to do manually.
    </p>
    <p class="govuk-body">
        Often, role templates are written like job adverts. Matchers have to parse
        complex technical language to understand what's being offered. Then they try to
        decide which of the candidates they've seen would be well suited. This approach
        can be open to bias, as certain candidates might stick in the mind more than others.
        It also lacks transparency and objectivity. A different matcher might make a different
        decision, and it's often done on instinct or gut feeling rather than anything quantifiable.
    </p>
    <p class="govuk-body">
        In addition, because these templates are put together in word-processing software,
    they're not optimised to be viewed on the internet. The data within them is also
    locked away. As a senior leader, it's vital that you know what people on your
        development schemes are being asked to do. These requests often indicate critical
        gaps in your organisation's capability - but even the most committed senior leader
    might hesitate at reviewing three or four hundred pages of prose.
    </p>
    <p class="govuk-body">
        The approach I've taken with this software is that the role profile is for the
    candidate to read: it should give them a strong flavour of what they'll be doing.
    However, the information that's important to the matcher is whether it will stretch
    the individual. I've quantified this with scales of 0-5.
    </p>
    <p class="govuk-body">
        I've also chosen an algorithm that optimises for the best overall outcome. In the
    next few pages I'll take you through a worked example, as well as explaining why I think
    this problem is much harder than it first appears.
    </p>

    <a href="{{ url_for("pitch.problem") }}" class="govuk-button">Continue</a>
{% endblock %}

app/templates/pitch/start.html
{% extends "base.html" %}

{% block content %}
    <h2 class="govuk-heading-l">
        A niche solution to a niche problem
    </h2>
    <p class="govuk-body-lead">
        A development programme is a good and worthy thing to run. Moving bright people around
        the business to help them understand the complexity and intricacies of the
        organisation they're joining is vital to help them become leaders.
    </p>
    <p class="govuk-body">
        However: matching people with jobs that will stretch and grow them as employees
        is very difficult. It's a problem that doesn't seem difficult at first, but
        hopefully through this presentation I'll be able to show you what a wicked problem
        it is...
    </p>
    <p class="govuk-body">
        ...and a solution to the problem that could save you money and free up your
        staff to do exciting, valuable work.
    </p>

    <a href="{{ url_for("pitch.problem") }}" role="button" draggable="false" class="govuk-button govuk-button--start" data-module="govuk-button">
  Start now
  <svg class="govuk-button__start-icon" xmlns="http://www.w3.org/2000/svg" width="17.5" height="19" viewBox="0 0 33 40" aria-hidden="true" focusable="false">
    <path fill="currentColor" d="M0 0h13l20 20-20 20H0l20-20z" />
  </svg>
</a>
{% endblock %}

app/templates/pitch/the-approach.html
{% extends "base.html" %}

{% block content %}
<h2 class="govuk-heading-l">
    Testing the theory
</h2>

    <table class="govuk-table">
        <caption class="govuk-table__caption">Random pairings</caption>
        <thead class="govuk-table__head">
        <tr class="govuk-table__row">
            <th scope="col" class="govuk-table__header"></th>
            <th scope="col" class="govuk-table__header">A</th>
            <th scope="col" class="govuk-table__header">B</th>
            <th scope="col" class="govuk-table__header">C</th>
            <th scope="col" class="govuk-table__header">D</th>
            <th scope="col" class="govuk-table__header">E</th>
            <th scope="col" class="govuk-table__header">F</th>
            <th scope="col" class="govuk-table__header">G</th>
            <th scope="col" class="govuk-table__header">H</th>
            <th scope="col" class="govuk-table__header">I</th>
            <th scope="col" class="govuk-table__header">J</th>

        </tr>
        </thead>
        <tbody class="govuk-table__body">
        {% for row in data %}
            {% set j = loop.index %}
            {% include "partials/table-row.html" %}
        {% endfor %}

  </tbody>
</table>

    <form class="govuk-form-group" action="{{ url_for("pitch.solution") }}" method="post">
        <div class="input submit">
            <input type="submit" value="Solve" class="govuk-button">
        </div>
    </form>
{% endblock %}

app/templates/pitch/the-problem.html
{% extends "base.html" %}

{% block content %}
    <h1 class="govuk-heading-l">
        A worked example
    </h1>
    <p class="govuk-body-l">
        This is a very rough example. I've used a limited number of criteria for the sake
    of brevity. The system at scale could operate with as many data points as are required.
    </p>
    <p class="govuk-body">
        Let's suppose your organisation has four key competences: Digital,
        Finance, Operations, and Policy. Let's suppose also that it's the first year of
    your development scheme: you've hand-picked Aisha, who's a rising star in Digital.
        She scores her knowledge in each key competency as follows:</p>
    <p class="govuk-body">
    <code>
        Aisha
        <br>
        <br>
        Digital: 4/5<br>
        Policy: 2/5<br>
        Operations: 1/5<br>
        Finance: 0/5<br>
    </code>
    </p>

    <p class="govuk-body">
        The only role available for this development scheme in this rotation is
        Assistant Head of Finance. We can rate this role on the same scale as above:
    </p>
    <p class="govuk-body">
        <code>
            Assistant Head of Finance
            <br>
            <br>
            Digital: 1/5 <br>
            Policy: 1/5 <br>
            Operations: 0/5 <br>
            Finance: 5/5 <br>
        </code>
    </p>
    <p class="govuk-body">
        We could now work out a number that represents how well this candidate and role
    are suited to each other. For the sake of this example, I'm going to assume that
        we want Aisha to do something she's not good at - Policy, Operations, or Finance.
        To do that, I'll use a calculation that gives more weight to skills she doesn't have
    by subtracting her current level of skill from the maximum. If we wanted to focus on
        specialising, we'd use a different calculation.
    </p>
    <p class="govuk-body">
        <code>
            Aisha x Assistant Head of Finance
            <br>
            <br>
            Digital: (5-4) x 1 = 1 <br>
            Policy: (5-2) x 1 = 3 <br>
            Operations: (5-1) x 0 = 0 <br>
            Finance: (5-0) x 5 = 25 <br>
            <br>
            Total: 29
        </code>
    </p>
    <p class="govuk-body">
        Calculating the score like this gives us an objective measure of how well the
        candidate will be developed in any given role. This will be useful if we
        expand the development scheme, as we'll be able to compare pairings quickly.
    </p>
    <table class="govuk-table">
        <caption class="govuk-table__caption">One candidate and one role</caption>
        <thead class="govuk-table__head">
        <tr class="govuk-table__row">
            <th scope="col" class="govuk-table__header"></th>
            <th scope="col" class="govuk-table__header">Aisha</th>
        </tr>
        </thead>
        <tbody class="govuk-table__body">
        <tr class="govuk-table__row">
        <th scope="row" class="govuk-table__header">Assistant Head of Finance</th>
        <td class="govuk-table__cell">29</td>
        </tr>
  </tbody>
</table>
    <p class="govuk-body">
        As you can see, there's only one option: Aisha will take the Assistant Head of
        Finance role. And with two candidates and two roles, there's only two possibilities:
    </p>
    <table class="govuk-table">
        <caption class="govuk-table__caption">Two candidates and two roles</caption>
        <thead class="govuk-table__head">
        <tr class="govuk-table__row">
            <th scope="col" class="govuk-table__header"></th>
            <th scope="col" class="govuk-table__header">Aisha</th>
            <th scope="col" class="govuk-table__header">Benjamin</th>

        </tr>
        </thead>
        <tbody class="govuk-table__body">
        <tr class="govuk-table__row">
        <th scope="row" class="govuk-table__header">Assistant Head of Finance</th>
        <td class="govuk-table__cell">29</td>
        <td class="govuk-table__cell">19</td>

        </tr>
        <tr class="govuk-table__row">
        <th scope="row" class="govuk-table__header">Delivery Manager</th>
        <td class="govuk-table__cell">20</td>
        <td class="govuk-table__cell">29</td>

        </tr>
  </tbody>
</table>

    <p class="govuk-body">
        Aisha will still take the Assistant Head of Finance role, because it's a better
        fit, and Benjamin will only have one choice - whichever is left. Luckily, that's
        the best role for him too. At three, there are six possibilities:
    </p>
        <table class="govuk-table">
        <caption class="govuk-table__caption">Three candidates and three roles</caption>
        <thead class="govuk-table__head">
        <tr class="govuk-table__row">
            <th scope="col" class="govuk-table__header"></th>
            <th scope="col" class="govuk-table__header">Aisha</th>
            <th scope="col" class="govuk-table__header">Benjamin</th>
            <th scope="col" class="govuk-table__header">Carla</th>

        </tr>
        </thead>
        <tbody class="govuk-table__body">
        <tr class="govuk-table__row">
        <th scope="row" class="govuk-table__header">Assistant Head of Finance</th>
        <td class="govuk-table__cell">29</td>
        <td class="govuk-table__cell">20</td>
        <td class="govuk-table__cell">21</td>

        </tr>
        <tr class="govuk-table__row">
        <th scope="row" class="govuk-table__header">Delivery Manager</th>
        <td class="govuk-table__cell">21</td>
        <td class="govuk-table__cell">29</td>
        <td class="govuk-table__cell">18</td>
        </tr>

        <tr class="govuk-table__row">
        <th scope="row" class="govuk-table__header">Policy Lead</th>
        <td class="govuk-table__cell">18</td>
        <td class="govuk-table__cell">29</td>
        <td class="govuk-table__cell">18</td>
        </tr>
  </tbody>
</table>
<p class="govuk-body">
    The first candidate can choose (or be assigned) to any one of three roles. The
    second candidate can have a choice of two, and the last candidate gets whatever is
    left. There are six possibilities now: 3 x 2 x 1. This is usually written <var>3!</var>,
or three factorial.
</p>
    <p class="govuk-body">
        With ten candidates, there are ten factorial (<var>10!</var>) ways of combining them. <var>10!</var> is
        3,628,800 different possibilities. Every new pair increases the number of
        combinations exponentially.
    </p>
    <p class="govuk-body">
        Having worked out an objective value for how stretching each role would be for each
    candidate, we can try our best to calculate the best pairing overall. Although we're
    doing this with numbers, this is exactly the same thing your staff are doing manually -
    trying to find great matches that will grow and develop your staff. On the next page,
    you'll see a table with only ten candidate and ten roles. I'd like you to try to find
    an answer. You can then compare with the computer-assisted answer.
    </p>



       <a href="{{ url_for("pitch.approach") }}" role="button" class="govuk-button govuk-button--start" data-module="govuk-button">Continue</a>
{% endblock %}

app/templates/pitch/the-solution.html
{% extends "base.html" %}
{% block content %}

<div class="govuk-grid-row">
    <div class="govuk-grid-column-one-third">
        <table class="govuk-table">
            <caption class="govuk-table__caption">Suggested pairings</caption>
            <thead class="govuk-table__header">
                <tr class="govuk-table__row">
                    <th scope="col" class="govuk-table__header"></th>
                    <th scope="col" class="govuk-table__header">Role</th>
                    <th scope="col" class="govuk-table__header">Candidate</th>
                    <th scope="col" class="govuk-table__header">Score</th>
                </tr>
            </thead>
            <tbody class="govuk-table__body">
                {% for answer in indexes %}
                    <tr class="govuk-table__row">
                        <th scope="row" class="govuk-table__header"></th>
                        <td class="govuk-table__cell">Role {{ answer[0] + 1 }}</td>
                        <td class="govuk-table__cell">{{ lookup.get(answer[1]) }}</td>
                        <td class="govuk-table__cell">{{ data[answer[0]][answer[1]] }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>

      <div class="govuk-grid-column-two-thirds">
        <table class="govuk-table">
        <caption class="govuk-table__caption">Random pairings</caption>
        <thead class="govuk-table__header">
        <tr class="govuk-table__row">
            <th scope="col" class="govuk-table__header"></th>
            <th scope="col" class="govuk-table__header">A</th>
            <th scope="col" class="govuk-table__header">B</th>
            <th scope="col" class="govuk-table__header">C</th>
            <th scope="col" class="govuk-table__header">D</th>
            <th scope="col" class="govuk-table__header">E</th>
            <th scope="col" class="govuk-table__header">F</th>
            <th scope="col" class="govuk-table__header">G</th>
            <th scope="col" class="govuk-table__header">H</th>
            <th scope="col" class="govuk-table__header">I</th>
            <th scope="col" class="govuk-table__header">J</th>

        </tr>
        </thead>
        <tbody class="govuk-table__body">
        {% for row in data %}
            {% set j = loop.index %}
            {% include "partials/table-row.html" %}
        {% endfor %}
        </tbody>
    </table>
      </div>
    </div>


    <a href="{{ url_for("pitch.approach") }}" role="button" draggable="false" class="govuk-button" data-module="govuk-button">
  Try again
  <svg class="govuk-button__start-icon" xmlns="http://www.w3.org/2000/svg" width="17.5" height="19" viewBox="0 0 33 40" aria-hidden="true" focusable="false">
    <path fill="currentColor" d="M0 0h13l20 20-20 20H0l20-20z" />
  </svg>
</a>
{% endblock %}

app/templates/profile/profile.html
{% extends "base.html" %}

{% block content %}
    <div class="govuk-accordion" data-module="govuk-accordion" id="accordion-default">
        <div class="govuk-accordion__section ">
            <div class="govuk-accordion__section-header">
                <h2 class="govuk-accordion__section-heading">
        <span class="govuk-accordion__section-button" id="accordion-default-heading-1">
          Career profile for {{ candidate.first_name }} {{ candidate.last_name }}
        </span>
                </h2>
            </div>
            <div id="accordion-default-content-1" class="govuk-accordion__section-content" aria-labelledby="accordion-default-heading-1">
                <p class='govuk-body'>{{ candidate.first_name }} is on the {{ candidate.specialism }} Fast Stream</p>
            </div>
        </div>

                {% for role in history %}
                    {% set loop_ = loop %}
                    {% include 'partials/accordion-section-role.html' %}
                {% endfor %}


    </div>

    {#          <ul class="govuk-list govuk-list--bullet">#}
    {#              <li>{{ candidate.first_name }} is on the FLS scheme</li>#}
    {#                {% if candidate.ethnicity.bame %}#}
    {#                    <li>They are eligible for META {% if application.meta %} and have taken up#}
    {#                    {% else %} but have not taken up{% endif %} the offer</li>#}
    {#                {% endif %}#}
    {#                {% if candidate.long_term_health_condition %}#}
    {#                    <li>They are eligible for DELTA {% if application.delta %} and have taken up#}
    {#                    {% else %} but have not taken up{% endif %} the offer</li>#}
    {#                {% endif %}#}
    {#            <li>They're in cohort {{ application.cohort }} on the#}
    {#                {{ application.scheme_start_date.year }} intake</li>#}
    {#              <li>This candidate is currently based in {{ candidate.current_location() }}</li>#}
    {#              {% if candidate.completed_fast_stream %}#}
    {#                  <li>They completed the Fast Stream</li>#}
    {#              {% endif %}#}
    {#              <li>They aspire to {{ application.aspirational_grade.value }}</li>#}
    {#          </ul>#}
    {#        </div>#}


{% endblock %}